### ISSUE TITLE
Stack depth instrumentation fails to account for the full function activation stack frame

### ISSUE THREAD

**Issue by nagisa** [paritytech/wasm-instrument#1]
The stack depth calculation for the `call` and `call_indirect` instruction  here

https://github.com/paritytech/wasm-utils/blob/b22696aaa516212284f2d94a28d8d292afe27859/src/stack_height/max_height.rs#L268-L293

fails to account for the full function activation frames as described in the [specification](https://webassembly.github.io/spec/core/exec/runtime.html#stack).

For that reason it is possible to write a WASM program which, when instrumented, could place frames onto the stack and overflow it regardless of the limit imposed.

Most straightforward such WASM module may look like this

```wast
(module
  (type (;0;) (func))
  (func (;0;) (type 0)
    call 0)
  (func (;1;) (type 0)
    call 0)
  (export "main" (func 1)))
```

which after instrumentation becomes

```wast
(module
  (type (;0;) (func))
  (func (;0;) (type 0)
    call 0)
  (func (;1;) (type 0)
    call 0)
  (global (;0;) (mut i32) (i32.const 0))
  (export "main" (func 1)))
```

today.

The correct model should be:

1. Pop the function address (for `call_indirect`);
2. Pop the arguments;
3. Push a function activation frame (this includes space for [arguments, locals, return values and a _reference to the module instance_](https://webassembly.github.io/spec/core/exec/runtime.html#activations-and-frames));

Module instance reference here in particular is something that would make stack depth accounting accurate in absence of the arguments, locals and return values.

**Comment by athei** [comment]
Good catch. I agree with everything written here. I checked the code and it should be enough it we push some constant for the two call instructions in `max_height::compute` (and pop it at function exit).

If a function isn't zero cost the metering code is injected **before** calling this function so everything should be A-okay. A regression test would be needed, though.

**Comment by athei** [comment]
Opened a PR that should fix this.
