### ISSUE TITLE
Update debug information when injecting gas metering

### ISSUE THREAD

**Issue by mangas** [paritytech/wasm-instrument#15]
Injecting the gas metering causes the function indices to shift. This causes any stacktraces using the name section to be wrong for any function with an index higher than the injected gas meter functions.

**Comment by athei** [comment]
This should be optional. When using this on chain like pallet-contracts does we certainly don't want to deal with strings.

**Comment by mangas** [comment]
changing the signature would be a breaking change, is it worth having a second `inject_with_debug` sort of thing?

**Comment by mangas** [comment]
Just to be clear, on my previous comment I'm assuming a scenario where there is debug information but by default it would not be changed. If those have no debug information then nothing happens.

**Comment by mangas** [comment]
@athei alternatively I can remove the parse_names and add a comment explaining that if you need the name section to be updated then parse_names needs to be called beforehand. It's not great but it solves the problem with less code
