### ISSUE TITLE
Expose more features from parity-wasm

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/wasm-instrument#4]
Only `sign_ext` feature is supported from parity-wasm, the following aren't, but might be useful:
* atomics
* bulk
* multi_value
* simd

I wanted to do some experiments with enabling various features, but it fails with errors like this:
```
170 |         match opcode {
    |               ^^^^^^ pattern `&Simd(_)` not covered
```

**Comment by pepyakin** [comment]
I am confused, how parity-db could be possibly related here?

**Comment by nazar-pc** [comment]
I'm sorry, it should have been `parity-wasm` of course :upside_down_face:

**Comment by athei** [comment]
We don't expose whole those features are in `parity-wasm` they are defunct. They won't pass the test suite. Also, guarding wasm proposals behind cargo features is a bad idea and doesn't scale. It just doesn't work well with feature unification and also makes the code very convoluted.

Instead, wasm features should be allowed or disallowed with a `Config` passed at runtime. We will do that when we switch to `wasmparser`. This will also unlock all features: https://github.com/paritytech/wasm-instrument/issues/3
